cache:
  root: ${ETHEREAL_CACHE_ROOT}

etherscan:
  mainnet:
    key: ${ETHEREAL_ETHERSCAN_MAINNET_KEY:X5QAW799H4EUJ81RB2F6HD5YW1MJUZEJ9Z}
  polygon:
    key: ${ETHEREAL_ETHERSCAN_POLYGON_KEY:GQEHVRGYTSTSG5W6P3FDAWHSVK4NADXKK7}
  avalanche:
    key: ${ETHEREAL_ETHERSCAN_AVALANCHE_KEY:4EUFN3TNZKDJFXK8PWCA63QRUHSNDPB2SF}
  ftm:
    key: ${ETHEREAL_ETHERSCAN_FTM_KEY:BHMA4EQG19NJ8ZDZWHNID9DRJ2EGN6HQB3}
  arbitrum:
    key: ${ETHEREAL_ETHERSCAN_ARBITRUM_KEY:HV27JNZG6AF6UEE2F9KEJSD3713SMN3RAP}
  optimism:
    key: ${ETHEREAL_ETHERSCAN_OPTIMISM_KEY:9N9DPD2T7FWG8RNWVIH36VM13S6P42898N}
